### ISSUE TITLE
How to prepare data for custom datasets

### ISSUE THREAD

**Issue by Winter-Dry** [markomih/ResFields#3]
Thanks for your wonderful work!
I want to train ResFields on our own video data from multiple cameras, like [neural 3d dataset format](https://github.com/facebookresearch/Neural_3D_Video), what should I do to adapt to this project?

Looking forward to your reply!

**Comment by markomih** [comment]
Hi Winter-Dry, thanks for your interest in our project. 

Our data format closely follows the format used in [NeuS](https://github.com/Totoro97/NeuS) and their preprocessing pipeline, with the only difference being that in our case each folder includes data from one camera. Please let us know if you face obstacles on the way.
