### ISSUE TITLE
Issues about running the example

### ISSUE THREAD

**Issue by sen-ye** [markomih/ResFields#5]
Hello, when I ran the example provided in the resfields module:

> m = Linear(20, 30, rank=10, capacity=100)
> input_x, input_time = torch.randn(128, 20), torch.randn(128) 
> output = m(input_x, input_time) 
> print(output.size())

I met the following problem:

> line 189, in forward
>     return torch.nn.functional.linear(input, weight.squeeze(0), self.bias)
> RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

How can I fix this problem? Thanks

**Comment by markomih** [comment]
Hi @sen-ye , 

Sorry, I forgot to update the docstring after updating the code. The forward function now expects one more dimension (the batch dimension). Here's a small working example:
```
batch_size = 128
n_points = 100
F_in, F_out = 20, 30
_rank = 10
_capacity = 100

input_x = torch.randn(batch_size, n_points, 20)
input_time = torch.randn(batch_size)

m = Linear(F_in, F_out, rank=_rank, capacity=_capacity, mode='interpolation')
output = m(input_x, input_time)
print(output.size())
# >>> torch.Size([128, 100, 30])
```

**Comment by sen-ye** [comment]
It works, thank you!
