### ISSUE TITLE
[Discussion] Intuition of this work

### ISSUE THREAD

**Issue by summertight** [markomih/ResFields#6]
Thank you for the nice work.

I want to ask something for the intuition or take-home-message of this work.

As you mentioned in the manuscript, increasing capacity for describing the high-frequency signal (time-dependent maybe), brutally increasing the depth or width of the MLPs is most straightforward and naive idea.
Yet, it is widely acknowledged that this approach is impractical.

Here, I wonder about the implications when the scenario involves a scarcity of temporal signals.
**When the time signal data is scarce(e.g., very short-term video or not much various postures smthng), simply increasing the depth or width of MLPs must cause overfitting which cannot interpolate the in-between of showed time signal (e.x, 1 and 2 are shown but the trained MLPs do not show plausible results in the 1.1, 1,2 or 1.5).** 

Do you believe ResFields' approach can assist MLPs in interpolating between displayed signals (perhaps leveraging underfitting's strength) without compromising the accurate reconstruction of the displayed signals (potentially harnessing overfitting's strength), especially in scenarios where there is a scarcity of displayed signals? In other words, can we achieve dual benefits with a single solution, akin to "killing two birds with one stone"?

Waiting for your opinion.

Thank you.

**Comment by markomih** [comment]
Hi @summertight,

Thank you for your interest in our work on ResFields. I apologize for the delayed response; I missed this discussion point earlier.

I believe that the ResField architecture can indeed assist in accurately capturing the training signal while maintaining good interpolation properties. However, to provide more concrete advice, I would need to understand the specific use case you have in mind.

Best,
Marko
