### ISSUE TITLE
[Question] How does ResFields work with K-Plane and HexPlane

### ISSUE THREAD

**Issue by phongnhhn92** [markomih/ResFields#7]
Hi,

I have just read your paper. From a 3D point p(x,y,z) at time t, we can get the interpolated features of 6 planes and I am not sure how can you add time-dependent residual weight to the plane-based methods such as K-plane and HexPlane. 

Thanks !

**Comment by markomih** [comment]
Hi @phongnhhn92, thank you for your interest in our work! 

K-planes/HexPlanes have an MLP that takes as input the interpolated features to predict color and density -- we implement this MLP with the ResField architecture.  

We further provide additional details regarding the HexPlane experiment in the appendix that might be relevant to your question. 
<img width="493" alt="image" src="https://github.com/markomih/ResFields/assets/13746017/0099cdf9-c268-4f36-9b01-ac62e312a1db">
