### ISSUE TITLE
ResFields + Dynamic Point Field?

### ISSUE THREAD

**Issue by fishfishson** [markomih/ResFields#8]
Dear author, 

Thx for sharing your great repo! I wonder whether ResFields can be applied to Dynamic Point Field? Maybe you have already tried it. Can you share your insights about it?

**Comment by markomih** [comment]
Hi @fishfishson,

Thanks for your interest in our work! 

Indeed we have tried DPF + ResFields for learning scene flows. Please see Section 4.4 in our paper for more details. 
On our setup (Tab. 5), we demonstrated that ResFields benefit learning scene flows, i.e. a smaller architecture with ResFields (128 neurons) achieves better results compared to a larger DPF (256 neurons).  

Best,
Marko

**Comment by fishfishson** [comment]
Hi, Marko

How about using DPF + ResField for dynmaic scene reconstruction or rendering?

**Comment by markomih** [comment]
Hi @fishfishson, 

We haven't directly tried DPF + resfields for the dynmaic scene reconstruction as it's unclear how to utilize DPF for 4D NeRFs. 

Best,
Marko
